name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# This profile is copied to a non-core location by
# \Drupal\Tests\config\Functional\ConfigInstallProfileUnmetDependenciesTest.
core_version_requirement: '*'
hidden: true
install:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2020-11-26
version: '8.9.10'
project: 'drupal'
datestamp: 1606360355
