name: Testing config overrides
type: profile
description: 'Minimal profile for running tests with config overrides in a profile.'
# version: VERSION
# core: 8.x
hidden: true
install:
  - action
  - language
  - tour

# Information added by Drupal.org packaging script on 2018-11-07
version: '8.6.3'
core: '8.x'
project: 'drupal'
datestamp: 1541602730
