name: 'Testing config import'
type: profile
description: 'Tests install profiles in the config importer.'
# version: VERSION
# core: 8.x
hidden: true
dependencies:
  - syslog
themes:
  - stark

# Information added by Drupal.org packaging script on 2016-11-02
version: '8.2.2'
core: '8.x'
project: 'drupal'
datestamp: 1478110097
