name: 'Settings Tray'
type: module
description: 'Allows users to directly edit the configuration of blocks on the current page.'
package: Core
# version: VERSION
# core: 8.x
dependencies:
  - drupal:block
  - drupal:toolbar
  - drupal:contextual

# Information added by Drupal.org packaging script on 2019-05-01
version: '8.7.0'
core: '8.x'
project: 'drupal'
datestamp: 1556737125
