name: 'Configuration Manager'
type: module
description: 'Allows administrators to import and export configuration changes.'
package: Core
# version: VERSION
core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2020-11-05
version: '8.9.8'
project: 'drupal'
datestamp: 1604595321
