name: 'Configuration Manager'
type: module
description: 'Allows administrators to manage configuration changes.'
package: Core
# version: VERSION
# core: 8.x
configure: config.sync

# Information added by Drupal.org packaging script on 2018-09-10
version: '8.6.1'
core: '8.x'
project: 'drupal'
datestamp: 1536585833
